### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by asardinha** [jnederlo/dfs_optimizers#1]
@jnederlo forked the repo and will begin working on some customization and pull accordingly. I'll also leave some comments on additional customization.

I'm the meantime, I can work on customizing for NHL Fanduel rules as well as MLB.

Looking forward to working with you on this project

**Comment by jnederlo** [comment]
@asardinha Awesome. I'll get the NBA one up shortly, but it's not done yet, as I'm struggling with some of the constraints for multiple positions. Depending on how we want to proceed with this, we can consider also making a python package, but let's just stick for personal use for now.

If you need any help with some of the installation like Cplex let me know.

**Comment by asardinha** [comment]
@jnederlo definitely having issues installing CPLEX, have the academic license, but can't seem to call the API or do a pip install.

Any advice?

**Comment by jnederlo** [comment]
Here's how you install the python API https://www.ibm.com/support/knowledgecenter/SSSA5P_12.7.1/ilog.odms.cplex.help/CPLEX/GettingStarted/topics/set_up/Python_setup.html 

In short: Find where you installed cplex - on my mac it's in: 

`/Applications/CPLEX_Studio_Community128`

then run:

`python setup.py install`

this will install it in you python packages directory, so make sure it goes to the right python packages. For example, I use python3 so I run 

`python3 setup.py install`

When I put this on my server and in my python virtual env I had to specify the location of my virtual env python packages like so

`python3 setup.py install --home yourvirtualenvpythonpackageshome/cplex`

Note I also had to go into the above home location (i.e. my virtual env python packages directory and move the cplex folder back a few directories because it was something like 'cplex/ibm/cplex'. So I moved the 2nd cplex to the root of the virtual env packages. Anyways, you probably won't have to do that.

Once you are able to run the setup script then you just follow the instructions and it should be good to go.

**Comment by jnederlo** [comment]
@asardinha I made the nhl optimizer with inheritance so now it is easy to add the Fanduel options. If you want to, go ahead and add in Fanduel. You can just make a new module called fanduel.py and make it more or less identical to draftkings.py. The only functions you will need to create will be the formulation (i.e. "type_1()" in DK) and fill_lineups(). Those are the functions you made changes to in your pull request to, so it should be pretty smooth to get it done.

**Comment by jnederlo** [comment]
@asardinha I went ahead and added fanduel for NHL. I also fixed the constraint so that no more than 4 players are included on 1 team.

**Comment by asardinha** [comment]
@jnederlo I was able to take some sabersim projections and backtest, using them, you can do pretty well if you are playing around with the stacking types.

As for next steps, is there anything you'd like to see or anything I can help with, before we move on? Right now, I'm reading through the PuLP documentation to see how/if it is possible to add in exposures to the .csv and limit player frequency. I've also experimented with using standard deviation to randomize the projection.

Either way, thanks for taking care of the FanDuel problem. Again, please let me know how I can help/contribute in any way.

**Comment by jnederlo** [comment]
@asardinha We could discuss different ways to test models. I've done a lot of back testing myself with my own projections and they do well, but I'm curious on what approach you are using to test your results? 

Just off the top of my head, in regards to adding player exposures, I think you would add constraints much the same way the overlap constraint is being added. You could check every previous lineup for a certain player (or all players), and make sure that the sum of their inclusions is less than some number (i.e. a number of 50 out of 150 lineups would put a max of 33% inclusion). Conversely, to make sure a player is included in at least some number of lineups, you would do something like add a new decision variable corresponding to whether that player is included in a lineup. You would check all previous lineups like we do in the overlap constraint, and would keep having the requirement of including that player in a lineup so long as the number of previous lineups that player is included in is less than some constant. This would guarantee to include that player in your first n lineups and then may or may not included him in the rest (you could also remove him or change the constraint so that he isn't included in any more lineups).

Regarding the next steps, I would like to add in other sports. Probably basketball and baseball next. Baseball will be very easy, but basketball is proving to be a bit of a challenge as they can be in multiple positions. Other than that, we could add some new features to NHL (like player exposures). Can you let me know what other features you are thinking about?

**Comment by asardinha** [comment]
@jnederlo As for how I backtest, I feel it might be a little primitive, but typically play around with the line stacking conditions and create 4/3/1 and 3/3/2 stacks. Depending on the size of the slate, I typically remove those on the fourth line and without a powerplay designation, to ensure I can use as much salary as I can (especially on very small slates 2-3). Right now, I've been messing around with randomizing projections based on a player's standard deviation of points for the year (not so good results as of late). Sometimes, with NHL being so volatile, it's pretty much a dice roll. I typically keep the overlap at 4, so that I can maximize the variance in lines. Backtesting is using FantasyCruncher Rewind over and over and over again to see if I can find any edge based on the slate, but again...variance. I hope this helps, I wouldn't be surprised, if I am doing things the hard way...haha.

I would be interested in seeing how you produce your projections, and how those work and how you can produce "accurate projections."

As for next steps, I would be curious to see if we can set exposures, or play around with min and max deviation. I quite haven't figured out how to use this as an advantage, but look at is as a means for generating some consistency in a volatile sport.

Also-In doing some extra digging, it looks like we may want to look into adding the Numpy module to the MLB model, so that we can create a circular array for batting order (1:9, 9,1,2,3...ect.)

Either way, please let me know how I can assist.

**Comment by brian-kreider** [comment]
Hi @jnederlo  -  I'm having trouble with the initial build for CPLEX on my Mac.  I seem to successfully install CPLEX via "python3 setup.py install" within my /Applications/CPLEX_Studio_Community128/python directory.  However, when I then navigate to /Users/stevepowers/Desktop/dfs_optimizers-master and attempt "python3 run_example.py", I get:  "PulpSolverError("CPLEX_PY: Not Available")."

It would seem that I need to fix my "yourvirtualenvpythonpackageshome/cplex" directory, but I'm not sure what I'm supposed to do here.  Have been Googling boards without success - hope to be in touch.

SP

**Comment by kcdc29** [comment]
Any progress on the NBA model?  I'm also having a hard time wrapping my head around how to model since the correlations between teammates vary across players, positions, etc.

@asardinha are you finding that an overlap of 4 reduces the variance of performance of the lineups even at small slates?

**Comment by jnederlo** [comment]
I built the nba model but don't have it in production form, and won't have time to add it in for a while. Perhaps in December I can get it up.

As for the overlap, an overlap of 4 does increase the variance, but might not be what you want in small slates. Depends on the inputs you are providing.

**Comment by value-x** [comment]
Able to install CPLEX but having difficulty running the example afterwards: getting an errorModuleNotFoundError: No module named 'nhl.fanduel' . Any advice?, very new to Python but fascinated with your work.

**Comment by value-x** [comment]
I was able to install CPLEX but when I try to run_examply.py I get ModuleNotFoundError: No module named 'nhl.fanduel'. I am new to Python, can you please assist?

**Comment by jnederlo** [comment]
@value-x I can't give you any help without some more information. Can you provide the error you are getting?

**Comment by value-x** [comment]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/mac/PycharmProjects/tensorenv/venv/run_example.py", line 3, in <module>
    from nhl.fanduel import Fanduel as NHLFanduel
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'nhl.fanduel'

**Comment by jnederlo** [comment]
I also need to know what you are trying to run. There is no information here that I can use to diagnose what's going on in your system. I suspect that you are trying to run the program from the wrong location.

**Comment by NahomTayeGH** [comment]
Have you finished the nba model if so can you share it pls?

**Comment by StevinoK** [comment]
Interesting problem that I just ran into today. Been using the builder with great success for a few weeks, but found that it refused to build lineups for slates with >16 teams (more than 8 games). I worry that this may be a problem come the NFL season, when the player pool is that much bigger. Is there something I'm doing wrong?
